server:
  address: 0.0.0.0
  port: 80
  servlet:
    context-path: /xy
    
spring:
  datasource:
    url: jdbc:mysql:///xy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # 纯数字必须加上双引号
    password: "000000"
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: wrc.xy.entity  # 注意：对应实体类的路径